spring:
  cloud:
    azure:
      credential:
        managed-identity-enabled: true
        client-id: ${SPN_ID}
      keyvault:
        secret:
          property-source-enabled: true
          property-sources:
            - endpoint: ${AZURE_KEYVAULT_URI}
  application:
    name: petstoreproductservice
  datasource:
    url: ${postgresProductServiceDBURL}
    username: ${postgresLoginName}
    password: ${postgresPassword}
server:
  port: ${PETSTOREPRODUCTSERVICE_SERVER_PORT:8080}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    ssl:
      enabled: false
    diskspace:
      enabled: false
