spring:
  application:
    name: petstorepetservice
  datasource:
    url: ${PETSTOREPETSERVICE_DB_HOST}
    username: ${DB_USER}
    password: ${DB_USER_PASSWORD}
server:
  port: ${PETSTOREPETSERVICE_SERVER_PORT:8081}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    ssl:
      enabled: false
    diskspace:
      enabled: false
